# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76658673dc3c0fc704cbd2d156d8a403e61200ffce81b1119aa56db0bdffc20533603702ef435fbb3696b5534f2c0eed0912753cb2140178faf7656d818b87c

test:
  secret_key_base: ba3f39811eebd3445483bee18b2444facd3c054f86442239f3d908e20cbbe837af74bc75534f6dd0328a5e79f915d5a41c448c1cb33db9cac78075b5df0ccc14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
